### ISSUE TITLE
Support sendRawEmail

### ISSUE THREAD

**Issue by Si1kIfY** [Si1kIfY/aws-ses-local#5]
[sendRawEmail(params = {}, callback)](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendRawEmail-property)

**Comment by cayter** [comment]
Any timeline for this?

**Comment by Si1kIfY** [comment]
Hmm, I could probably spend some time on it this weekend but no specific timeline as yet.

PR's welcome if you have time :+1:

**Comment by camjackson** [comment]
I'm going to have a go at implementing this as I need it for my project :)

**Comment by camjackson** [comment]
@cayter in case you didn't see, this is done now!
